version: 1.0
app:
  # build id to deploy
  version: ""

  # configure public endpoint
  endpoints: public

  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1

  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    cpu: 1
    # memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb

  # List of environment variables that are set for the application
  # Liberty encrypted values are supported only if referenced in server.xml
  env:
    - name: JVM_ARGS 
      value: "-DenvironmentType=stage"
    - name: tradeDbHost
      value: "9938aec0-8105-433e-8bf9-0fbb7e483086.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud"
      #value: "easej-svt-vm.purple-mystic-butterfly.com"
    - name: tradeDbName
      value: bludb
      #value: tradedb
    - name: tradeDbPort
      value: "32459"
      #value: "60005"
    - name: dbUser
      value: lnl43017
      #value: "db2inst1"
    - name: dbPass
      value: "{xor}G2cNDxYYCCU9HDI0OggaJQ=="
      #value: "{xor}Oz1tLz4sLChvLTs="
    - name: sslconn
      value: "true"
      #value: "false"
    - name: QueueManager
      value: QM1
    - name: sslciphersuite
      value: "SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      #value: 'TLS_AES_128_GCM_SHA256'
    - name: mqHost
      value: 'qm1-7ede.qm.us-south.mq.appdomain.cloud' #hostname where MQ container is running
    - name: mqPort
      value: "31413"
    - name: mqChannel
      value: "CLOUD.APP.SVRCONN"
    - name: mqUser
      value: "app"
    - name: mqPass
      #value: "{aes}ACGv685f2PtN9s2NlsmLyRRJd8dxOSzyWXOl5JWJ/QjQDZ/GgZdyU3KrkHib+vx2QKoCPDHETwBcNs6c3W0UDiyuJiRk6ph/TwOCyxxFJYJm"
      value: "{xor}DAUyFjoRCSoxEisbGBoTEzBnBzw9azEmLDoAMxgcMRY5BS8GMygWaDwVMWs="

  # List of variables that can be referenced in server.xml
  # Liberty encrypted values are supported
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
